frontend/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, HiddenField, IntegerField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Register')


class ItemForm(FlaskForm):
    book_id = HiddenField(validators=[DataRequired()])
    quantity = HiddenField(validators=[DataRequired()])

frontend/api/__init__.py
USER_API_URL = 'http://user-service-c:5001'
BOOK_API_URL = 'http://book-service-c:5002'
ORDER_API_URL = 'http://order-service-c:5003'

frontend/app.py
from flask import Flask
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from routes import blueprint

app = Flask(__name__, static_folder='static')

app.config['SECRET_KEY'] = 'KwsJpGfCDlcP77okfHAtpbo-F_c'
app.config['WTF_CSRF_SECRET_KEY'] = 'yLnLKAJ3UuK8cEqmNucvLAuusjY'
app.config['UPLOAD_FOLDER'] = 'static/images'

app.register_blueprint(blueprint)

login_manager = LoginManager(app)
login_manager.init_app(app)
login_manager.login_message = "Please login."
login_manager.login_view = 'frontend.login'

bootstrap = Bootstrap(app)


@login_manager.user_loader
def load_user(user_id):
    return None

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5000)

frontend/routes.py
from flask import Blueprint, render_template, session, redirect, request, flash, url_for
from flask_login import current_user
import forms
from api.book_client import BookClient
from api.user_api import UserClient
from api.order_client import OrderClient

blueprint = Blueprint('frontend', __name__)


@blueprint.context_processor
def cart_count():
    count = 0
    order = session.get('order')
    if order:
        for item in order.get('order_items'):
            count += item['quantity']

    return {'cart_items': count}


@blueprint.route('/', methods=['GET'])
def index():
    if current_user.is_authenticated:
        session['order'] = OrderClient.get_order_from_session()
    try:
        books = BookClient.get_books()
        print("Fetched books:", books)  # Debug: Print the books dictionary to console
    except Exception as e:
        print(f"Error fetching books: {e}")  # Debug: Print any errors
        books = {'results': []}

    return render_template('index.html', books=books)


@blueprint.route('/register', methods=['POST', 'GET'])
def register():
    form = forms.RegistrationForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            username = form.username.data

            if UserClient.user_exists(username):
                flash("Please try another user name")
                return render_template('register.html', form=form)
            else:
                user = UserClient.create_user(form)
                if user:
                    flash("Registered. Please login.")
                    return redirect(url_for('frontend.index'))
        else:
            flash("Errors")

    return render_template('register.html', form=form)


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = forms.LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            api_key = UserClient.login(form)
            if api_key:
                session['user_api_key'] = api_key
                user = UserClient.get_user()
                session['user'] = user['result']

                order = OrderClient.get_order()
                if order.get('result'):
                    session['order'] = order['result']

                flash('Welcome back')
                return redirect(url_for('frontend.index'))
            else:
                flash('Cannot Login')
        else:
            flash('Cannot Login')

    return render_template('login.html', form=form)


@blueprint.route('/logout', methods=['GET'])
def logout():
    session.clear()
    flash('Logged out')
    return redirect(url_for('frontend.index'))


@blueprint.route('/book/<slug>', methods=['GET', 'POST'])
def book_details(slug):
    response = BookClient.get_book(slug)
    book = response['result']

    form = forms.ItemForm(book_id=book['id'])

    if request.method == 'POST':
        if 'user' not in session:
            flash("Please Login")
            return redirect(url_for('frontend.login'))

        order = OrderClient.add_to_cart(book_id=book['id'], quantity=1)
        session['order'] = order['result']
        flash("Book added to the cart")

    return render_template('book_info.html', book=book, form=form)


@blueprint.route('/checkout', methods=['GET'])
def checkout():
    if 'user' not in session:
        flash("Please Login")
        return redirect(url_for('frontend.login'))

    if 'order' not in session:
        flash("Please add some books to the cart")
        return redirect(url_for('frontend.index'))

    order = OrderClient.get_order()

    if len(order['result']['order_items']) == 0:
        flash("Please add some books to the cart")
        return redirect(url_for('frontend.index'))

    OrderClient.checkout()

    return redirect(url_for('frontend.thank_you'))


@blueprint.route('/thank_you', methods=['GET'])
def thank_you():
    if 'user' not in session:
        flash("Please Login")
        return redirect(url_for('frontend.login'))

    if 'order' not in session:
        flash("Please add some books to the cart")
        return redirect(url_for('frontend.index'))

    session.pop('order', None)
    flash("Thank you for shopping with us")

    return render_template('thankyou.html')

frontend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
          crossorigin="anonymous">

    {% block styles %}{% endblock %}

    <title>{% block title %} {% endblock %}</title>
</head>
<body>

{#nav bar beings#}
{#---------------------------#}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Book Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="/">Home</a>
                {% if not session['user'] %}
                    <a class="nav-link" href="/login">Login</a>
                    <a class="nav-link" href="/register">Register</a>
                {% else %}
                    {% if session['role'] is true %}
                        <a class="nav-link" href="/admin">Dashboard</a>
                        <a class="nav-link" href="/logout">Logout</a>
                    {% else %}
                        <a class="nav-link" href="/logout">Logout</a>
                    {% endif %}
                {% endif %}
                <a class="nav-link" href="/checkout">Checkout <span class="badge rounded-pill bg-light text-dark">{{ cart_items }} </span></a>
            </div>
        </div>
    </div>
</nav>

<div class="container">
    {#---------------------------#}
    {#nav bar ends#}
    {#messages negin#}
    {#---------------------------#}
    {% for message in get_flashed_messages() %}
        <div class="alert alert-primary alert-dismissible fade show mt-3 mb-3" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

    {% endfor %}
    {#---------------------------#}
    {#messages end#}

    {% block pageContent %}

    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
            crossorigin="anonymous"></script>

</div>
</body>
</html>

frontend/templates/book_info.html
{% extends "base.html" %}

{% block title %}Home Page{% endblock %}

{% block pageContent %}

    {% set url = "/book/" + book.slug %}
    {% set imageSRC = "images/" + book.image %}

    <div class="d-flex align-items-center justify-content-center">
        <div class="col-md-4 mt-5">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top"
                     alt="" style="width: 100%; display: block;"
                     src="{{ url_for('static', filename=imageSRC) }}"
                     data-holder-rendered="true">
                <div class="card-body">
                    <p class="card-text">Price: {{ book.price }} $</p>
                    <div class="d-flex justify-content-between align-items-center ">
                        <form method="POST">
                            {{ form.hidden_tag() }}
                            <button type="submit" class="btn btn-lg btn-outline-secondary " id="buy-now">Add To Cart
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock %}

frontend/templates/index.html
{% extends "base.html" %}
{% block title %}Home Page{% endblock %}

{% block pageContent %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% if books.results | length > 0 %}
                    {% for book in books.results %}
                        {% set url = url_for('frontend.book_details', slug=book.slug) %}
                        {% set book_cover = "images/" + book.image %}
                        <div class="col-md-3">
                            <div class="card mb-4 box-shadow">
                                <img class="card-img-top"
                                     alt="{{ book.title }}" style="width: 100%; display: block;"
                                     src="{{ url_for('static', filename=book_cover) }}"
                                     data-holder-rendered="true">
                                <div class="card-body">
                                    <p class="card-text">Price: {{ book.price }} $</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <a href="{{ url }}" class="btn btn-sm btn-outline-secondary">View Details</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <strong>No books found.</strong>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

frontend/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block pageContent %}

    <div class="container mt-5" style="max-width: 500px">
        <h1>Login</h1>
        <strong>{{ message }}</strong>
        <!-- Login form -->
        <form method="post">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.username.label(class_="form-label mt-3") }}:
                {{ form.username(class_="form-control") }}
            </div>
            <div class="form-group">
                {{ form.password.label(class_="form-label  mt-3") }}:
                {{ form.password(class_="form-control") }}
            </div>
            {{ form.submit(class_="w-100 btn btn-primary mt-3") }}

        </form>
    </div>

{% endblock %}


frontend/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}

{% block pageContent %}
        <div class="container mt-5" style="max-width: 500px">
        <h1>Register</h1>
        <strong>{{ message }}</strong>
        <!-- Register form -->
        <form method="post">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.username.label(class_="form-label") }}:
                {{ form.username(class_="form-control") }}
            </div>
            <div class="form-group">
                {{ form.password.label(class_="form-label") }}:
                {{ form.password(class_="form-control") }}
            </div>
            {{ form.submit(class_="w-100 btn btn-primary mt-3") }}

        </form>
    </div>
{% endblock %}

frontend/templates/thankyou.html
{% extends "base.html" %}
{% block title %}Thank you{% endblock %}

{% block pageContent %}
    <h1>Thank you</h1>
    <p>your order is being processed</p>
{% endblock %}